# This file is part of TinyverseGP | https://github.com/GPBench/TinyverseGP
# License: GPL-3.0-or-later

[project]
name = "tinyversegp"
version = "0.1.0"
description = "Minimalistic implementations of different representations for Genetic Programming"
authors = [
    { name = "Marie A." },
    { name = "Roman Kalkreuth" },
    { name = "Fabricio Olivetti de Franca" },
    { name = "Dominik Sobania" },
    { name = "Giovanni Squillero" },
    { name = "Alberto Tonda" },
    { name = "Zdenek Vasicek" },
]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "genetic programming",
    "evolutionary computation"
]
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Natural Language :: English",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
]
urls.homepage = "https://github.com/GPBench/TinyverseGP"
urls.documentation = "https://gpbench.github.io/TinyverseGP/"

dependencies = [
    "box2d >=2.3.10",
    "pygame >=2.6.1",
    "gymnasium >=1.0.0",
    "minatar>=1.0.15",
    "numpy >=2.1",
    "dd >=0.5.0",
    "sympy >=1.13",
    "requests >=2.32",
    "opencv-python >=4.11",
    "ale_py >=0.10.1",
    "icecream >=2.1.5",
    "configspace >=1.2.1",
    "pyyaml >=6.0.2",
    "smac >=2.3.1",
    "dill >=0.4.0",
]

[project.optional-dependencies]
llm = [
    "langchain_huggingface",
    "transformers",
    "openai",
    "torch"
]
dev = ["tinyversegp[test, tooling]"]
test = ["pytest>=7", "pytest-cov", "pytest_cases"]
tooling = ["mypy", "pre-commit", "ruff", "types-pyyaml"]

[tool.pytest.ini_options]
testpaths = ["test"]
minversion = "7.0"
log_cli = false
log_level = "DEBUG"
xfail_strict = true
addopts = "--durations=10 -vv"
markers = ["example: An example"]

# https://github.com/charliermarsh/ruff
[tool.ruff]
target-version = "py38"
line-length = 88
output-format = "full"
src = ["src", "tests"]
